name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Deploy this tag to production'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Dutluk'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6CFB0BE8D86A4328862E59429029B565 }}
        package: '*.jar'
